services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  mhujer.jms_serializer.uuid.uuid_serializer_handler:
    class: Mhujer\JmsSerializer\Uuid\UuidSerializerHandler
    tags:
      - { name: jms_serializer.subscribing_handler }

  lenats.jms_serializer.datetime.date_rfc3339_handler:
    class: LeNats\Services\DateRFC3339Handler
    tags:
      - { name: jms_serializer.subscribing_handler }

  LeNats\:
    resource: '../../{Services,Listeners,Commands}'

  LeNats\Listeners\:
    public: true
    resource: '../../Listeners/{*Listener.php,Responses/*Listener.php}'

  LeNats\Contracts\BufferInterface: '@LeNats\Services\StringBuffer'

  LeNats\Subscription\Subscriber:
    autowire: true

  LeNats\Subscription\CloseConnection:
    autowire: true

  LeNats\Subscription\Publisher:
    autowire: true
    arguments:
      $suffixes: '%lenats.event.suffixes%'

  LeNats\Subscription\Connector:
    autowire: true

  LeNats\Services\EventTypeResolver:
    arguments:
      - '%lenats.event.types%'

  LeNats\Services\Configuration:
    arguments:
      - '%lenats.configuration%'
